language: node_js
node_js:
  - "stable"
install:
  - npm install
script:
  - npm test

after_script: istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/PokemonServicesApi/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
